/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { Identifier } from './components/shared/identifier';
import { Variant } from './components/molecules/ana-votes/ana-votes';
export namespace Components {
  interface AnaButton {
    content?: string;
    icon?: string;
    identifier?: Identifier;
    selected?: boolean;
    type: 'primary' | 'secondary' | 'action' | 'tab';
  }
  interface AnaDropdown {
    close: () => Promise<void>;
    elevated: boolean;
    open: () => Promise<void>;
    shape: 'round' | 'smooth' | 'sharp';
    toggle: () => Promise<void>;
    type: 'primary' | 'secondary' | 'action';
  }
  interface AnaImage {
    alt: string;
    shape?: 'round' | 'smooth' | 'sharp';
    size?: 'large' | 'medium' | 'small' | 'xsmall';
    src: string;
  }
  interface AnaTabs {
    buttonType?: 'primary' | 'secondary' | 'action' | 'tab';
    tabs: any;
  }
  interface AnaTitle {
    color?: string;
    content: string;
    elevated: boolean;
    size?: 'large' | 'medium' | 'small';
  }
  interface AnaVotes {
    identifier?: string;
    totalVotes: number;
    variant?: Variant;
  }
}
declare global {
  interface HTMLAnaButtonElement extends Components.AnaButton, HTMLStencilElement {}
  var HTMLAnaButtonElement: {
    prototype: HTMLAnaButtonElement;
    new (): HTMLAnaButtonElement;
  };
  interface HTMLAnaDropdownElement extends Components.AnaDropdown, HTMLStencilElement {}
  var HTMLAnaDropdownElement: {
    prototype: HTMLAnaDropdownElement;
    new (): HTMLAnaDropdownElement;
  };
  interface HTMLAnaImageElement extends Components.AnaImage, HTMLStencilElement {}
  var HTMLAnaImageElement: {
    prototype: HTMLAnaImageElement;
    new (): HTMLAnaImageElement;
  };
  interface HTMLAnaTabsElement extends Components.AnaTabs, HTMLStencilElement {}
  var HTMLAnaTabsElement: {
    prototype: HTMLAnaTabsElement;
    new (): HTMLAnaTabsElement;
  };
  interface HTMLAnaTitleElement extends Components.AnaTitle, HTMLStencilElement {}
  var HTMLAnaTitleElement: {
    prototype: HTMLAnaTitleElement;
    new (): HTMLAnaTitleElement;
  };
  interface HTMLAnaVotesElement extends Components.AnaVotes, HTMLStencilElement {}
  var HTMLAnaVotesElement: {
    prototype: HTMLAnaVotesElement;
    new (): HTMLAnaVotesElement;
  };
  interface HTMLElementTagNameMap {
    'ana-button': HTMLAnaButtonElement;
    'ana-dropdown': HTMLAnaDropdownElement;
    'ana-image': HTMLAnaImageElement;
    'ana-tabs': HTMLAnaTabsElement;
    'ana-title': HTMLAnaTitleElement;
    'ana-votes': HTMLAnaVotesElement;
  }
}
declare namespace LocalJSX {
  interface AnaButton {
    content?: string;
    icon?: string;
    identifier?: Identifier;
    onButtonClicked?: (event: CustomEvent<Identifier>) => void;
    selected?: boolean;
    type?: 'primary' | 'secondary' | 'action' | 'tab';
  }
  interface AnaDropdown {
    elevated?: boolean;
    shape?: 'round' | 'smooth' | 'sharp';
    type?: 'primary' | 'secondary' | 'action';
  }
  interface AnaImage {
    alt: string;
    shape?: 'round' | 'smooth' | 'sharp';
    size?: 'large' | 'medium' | 'small' | 'xsmall';
    src: string;
  }
  interface AnaTabs {
    buttonType?: 'primary' | 'secondary' | 'action' | 'tab';
    onTabChange?: (event: CustomEvent<string>) => void;
    tabs?: any;
  }
  interface AnaTitle {
    color?: string;
    content: string;
    elevated?: boolean;
    size?: 'large' | 'medium' | 'small';
  }
  interface AnaVotes {
    identifier?: string;
    onVotesDecremented?: (event: CustomEvent<Identifier>) => void;
    onVotesIncremented?: (event: CustomEvent<Identifier>) => void;
    totalVotes: number;
    variant?: Variant;
  }
  interface IntrinsicElements {
    'ana-button': AnaButton;
    'ana-dropdown': AnaDropdown;
    'ana-image': AnaImage;
    'ana-tabs': AnaTabs;
    'ana-title': AnaTitle;
    'ana-votes': AnaVotes;
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'ana-button': LocalJSX.AnaButton & JSXBase.HTMLAttributes<HTMLAnaButtonElement>;
      'ana-dropdown': LocalJSX.AnaDropdown & JSXBase.HTMLAttributes<HTMLAnaDropdownElement>;
      'ana-image': LocalJSX.AnaImage & JSXBase.HTMLAttributes<HTMLAnaImageElement>;
      'ana-tabs': LocalJSX.AnaTabs & JSXBase.HTMLAttributes<HTMLAnaTabsElement>;
      'ana-title': LocalJSX.AnaTitle & JSXBase.HTMLAttributes<HTMLAnaTitleElement>;
      'ana-votes': LocalJSX.AnaVotes & JSXBase.HTMLAttributes<HTMLAnaVotesElement>;
    }
  }
}
