name: 'Chromatic'
on: push
jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
        # working-directory: playground
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: playground
          projectToken: d2e8371977de